# Generated by Django 3.1.4 on 2021-01-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(default=('medic', 'Medical team'), max_length=50)),
                ('path_type', models.CharField(default=('line', 'Straight line'), max_length=50)),
                ('localization', models.CharField(max_length=500)),
                ('station', models.CharField(max_length=500)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
