# Generated by Django 3.1.4 on 2021-01-18 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placefinder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='station',
            new_name='destination',
        ),
    ]
