# Generated by Django 3.1.4 on 2020-12-22 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placefinder', '0002_auto_20201215_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune_name', models.CharField(max_length=50)),
                ('district_name', models.CharField(max_length=50)),
                ('province_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='destination',
            new_name='station',
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField()),
                ('station_name', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
                ('address_street', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placefinder.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placefinder.commune'),
        ),
    ]
