# Generated by Django 3.1.4 on 2020-12-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placefinder', '0003_auto_20201222_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='location',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='station',
            field=models.CharField(max_length=500),
        ),
    ]
