# Generated by Django 3.1.4 on 2020-12-22 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placefinder', '0004_auto_20201222_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='location',
            new_name='localization',
        ),
        migrations.RemoveField(
            model_name='station',
            name='address_street',
        ),
        migrations.RemoveField(
            model_name='station',
            name='city',
        ),
        migrations.RemoveField(
            model_name='station',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='station',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='station',
            name='station_id',
        ),
        migrations.RemoveField(
            model_name='station',
            name='station_name',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Commune',
        ),
    ]
