# Generated by Django 3.1.4 on 2021-01-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placefinder', '0005_auto_20201223_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='type',
            field=models.CharField(default='medic', max_length=50),
        ),
    ]
