# Generated by Django 3.1.4 on 2021-01-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placefinder', '0006_measurement_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='type',
            new_name='path_type',
        ),
        migrations.AddField(
            model_name='measurement',
            name='content_type',
            field=models.CharField(default='line', max_length=50),
        ),
    ]
